Repository Pondae/finalProjectIR, pull requests merged in 2022-03, with the labels that each got.

#9 Searching by title
  back-end-project-2/Recipe_dev.py
Labels: enhancement

#10 Searching by Ingredients
  back-end-project-2/Recipe_dev.py
Labels: enhancement

#20 frontend searching by name and link to backend
  front-end-termproject-2/package-lock.json
  front-end-termproject-2/src/assets/list.png
  front-end-termproject-2/src/components/LyricformSong.vue
  front-end-termproject-2/src/components/SearchBM25.vue
  front-end-termproject-2/src/components/SearchName.vue
  front-end-termproject-2/src/components/SearchTF.vue
  front-end-termproject-2/src/components/SongfromArt.vue
  front-end-termproject-2/src/router/index.js
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/views/SearchAS.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement

#22 edit to top 3
  README.md
  back-end-project-2/Recipe_dev.py
Labels: bug

#26 edit clean data
  back-end-project-2/Recipe_dev.py
Labels: bug

#28 Dev2
  front-end-termproject-2/package-lock.json
  front-end-termproject-2/src/assets/list.png
  front-end-termproject-2/src/components/LyricformSong.vue
  front-end-termproject-2/src/components/SearchBM25.vue
  front-end-termproject-2/src/components/SearchIngredients.vue
  front-end-termproject-2/src/components/SearchName.vue
  front-end-termproject-2/src/components/SearchTF.vue
  front-end-termproject-2/src/router/index.js
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/views/SearchAS.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement

#32 Connect to db
  back-end-project-2/Recipe_dev.py
  back-end-project-2/__pycache__/Recipe_dev.cpython-39.pyc
  back-end-project-2/flaskproject.py
  front-end-termproject-2/src/App.vue
  front-end-termproject-2/src/components/SearchIngredients.vue
  front-end-termproject-2/src/components/SearchName.vue
  front-end-termproject-2/src/router/index.js
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/store/index.js
  front-end-termproject-2/src/views/Login.vue
  front-end-termproject-2/src/views/MarkProfile.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement

#36 set up unmark in frontend and backend
  back-end-project-2/Recipe_dev.py
  back-end-project-2/__pycache__/Recipe_dev.cpython-39.pyc
  back-end-project-2/flaskproject.py
  front-end-termproject-2/src/components/Mark_fav.vue
  front-end-termproject-2/src/components/SearchIngredients.vue
  front-end-termproject-2/src/components/SearchMark.vue
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/store/index.js
  front-end-termproject-2/src/views/MarkProfile.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement

#39 spell correction 1
  back-end-project-2/Recipe_dev.py
Labels: documentation

#42 Return picture
  back-end-project-2/Recipe_dev.py
  back-end-project-2/__pycache__/Recipe_dev.cpython-39.pyc
  back-end-project-2/flaskproject.py
  front-end-termproject-2/package-lock.json
  front-end-termproject-2/src/App.vue
  front-end-termproject-2/src/components/Mark_fav.vue
  front-end-termproject-2/src/components/SearchIngredients.vue
  front-end-termproject-2/src/components/SearchName.vue
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/views/Login.vue
  front-end-termproject-2/src/views/MarkProfile.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement

#45 Handle many user
  back-end-project-2/Recipe_dev.py
  back-end-project-2/__pycache__/Recipe_dev.cpython-39.pyc
  back-end-project-2/flaskproject.py
  front-end-termproject-2/src/components/Mark_fav.vue
  front-end-termproject-2/src/components/SearchIngredients.vue
  front-end-termproject-2/src/components/SearchMark.vue
  front-end-termproject-2/src/components/SearchName.vue
  front-end-termproject-2/src/router/index.js
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/store/index.js
  front-end-termproject-2/src/views/Login.vue
  front-end-termproject-2/src/views/MarkProfile.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement

#46 Version 6
  back-end-project-2/Recipe_dev.py
  back-end-project-2/__pycache__/Recipe_dev.cpython-39.pyc
  back-end-project-2/flaskproject.py
  front-end-termproject-2/package-lock.json
  front-end-termproject-2/src/App.vue
  front-end-termproject-2/src/components/Mark_fav.vue
  front-end-termproject-2/src/components/SearchIngredients.vue
  front-end-termproject-2/src/components/SearchMark.vue
  front-end-termproject-2/src/components/SearchName.vue
  front-end-termproject-2/src/router/index.js
  front-end-termproject-2/src/services/DataService.js
  front-end-termproject-2/src/store/index.js
  front-end-termproject-2/src/views/Login.vue
  front-end-termproject-2/src/views/MarkProfile.vue
  front-end-termproject-2/src/views/Searchlist.vue
Labels: enhancement
